# 使用基础镜像
FROM python:3.12

# 安装 Chrome 和 ChromeDriver
RUN apt-get update && apt-get install -y chromium chromium-driver

# 设置环境变量，指定 ChromeDriver 的路径
ENV CHROME_DRIVER_PATH /usr/lib/chromium/chromedriver

# 创建工作目录
WORKDIR /app

# 复制 Python 文件和所需的文件到容器中
COPY itvall.py .

# 安装 Python 依赖包
RUN pip install selenium requests eventlet futures

# 执行 Python 文件
CMD python itvall.py