name: IPTV Hebei

#on:
#  schedule:
#    - cron: '0 20 * * *' #早上2点
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures opencv-python eventlet

      #- name: Install Chrome WebDriver
        #run: |
          #LATEST_CHROMEDRIVER_VERSION=120.0.6099.109
          #curl -sS -o chromedriver_linux64.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-headless-shell-linux64.zip"
          #sudo unzip chromedriver_linux64.zip -d /usr/local/bin
          #rm chromedriver_linux64.zip
      #- name: Set chromedriver path
        #run: |
          #sudo ln -sf /usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chromedriver
          #sudo chmod +x /usr/local/bin/chromedriver
      - name: Run script
        run: python ${{ github.workspace }}/IPTV-hebei.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: iptv-hebei
          path: ${{ github.workspace }}/
          
      - name: 提交更改
        run: |
          git config --local user.email "ssili@126.com"
          git config --local user.name "ssili126"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull
          git push -f
